package markdown

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// supportedConstructs names every construct the subset renderer claims to
// support. Each entry must be the name of a fixture pair under testdata, so a
// construct cannot be claimed in the documentation without an example that is
// checked byte for byte.
var supportedConstructs = []string{
	"paragraphs",
	"headings",
	"emphasis",
	"strong",
	"inline_code",
	"fenced_code",
	"fenced_code_unterminated",
	"links",
	"images",
	"unordered_list",
	"ordered_list",
	"nested_list",
	"blockquote",
	"thematic_break",
	"hard_break",
	"autolink",
	"raw_html",
	"unsupported",
}

// fixtureNames lists the base names of every .md file under testdata.
func fixtureNames(t *testing.T) []string {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join("testdata", "*.md"))
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) == 0 {
		t.Fatal("no fixtures found under testdata")
	}
	names := make([]string, 0, len(paths))
	for _, p := range paths {
		names = append(names, strings.TrimSuffix(filepath.Base(p), ".md"))
	}
	return names
}

// TestFixtures renders every testdata/<name>.md and compares the result byte
// for byte with testdata/<name>.html. The expected files are written by hand
// from the specification, never generated by the renderer.
func TestFixtures(t *testing.T) {
	r := New()
	for _, name := range fixtureNames(t) {
		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join("testdata", name+".md"))
			if err != nil {
				t.Fatal(err)
			}
			want, err := os.ReadFile(filepath.Join("testdata", name+".html"))
			if err != nil {
				t.Fatal(err)
			}
			got := r.RenderHTML(string(src))
			if got != string(want) {
				t.Errorf("RenderHTML mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
			}
			assertNoRawMarkup(t, got)
		})
	}
}

// TestFixtureCoverage fails when a supported construct has no fixture, so the
// corpus cannot fall behind the feature list.
func TestFixtureCoverage(t *testing.T) {
	have := make(map[string]bool)
	for _, name := range fixtureNames(t) {
		have[name] = true
	}
	for _, construct := range supportedConstructs {
		if !have[construct] {
			t.Errorf("construct %q has no fixture testdata/%s.md", construct, construct)
		}
	}
}

// TestRendererInterface pins the decided API: the subset renderer satisfies
// Renderer, so a consumer can swap in a full CommonMark implementation.
func TestRendererInterface(t *testing.T) {
	var r Renderer = New()
	if got := r.RenderHTML(""); got != "" {
		t.Errorf("RenderHTML(%q) = %q, want %q", "", got, "")
	}
}

func TestEmptyAndBlankInput(t *testing.T) {
	r := New()
	for _, src := range []string{"", "\n", "   \n\n\t\n", "\r\n"} {
		if got := r.RenderHTML(src); got != "" {
			t.Errorf("RenderHTML(%q) = %q, want %q", src, got, "")
		}
	}
}

// TestCRLFNormalization checks that Windows and classic-Mac line endings
// produce the same output as Unix ones; the fixtures are all Unix.
func TestCRLFNormalization(t *testing.T) {
	r := New()
	want := r.RenderHTML("# Title\n\nA paragraph.\n")
	for _, src := range []string{"# Title\r\n\r\nA paragraph.\r\n", "# Title\r\rA paragraph.\r"} {
		if got := r.RenderHTML(src); got != want {
			t.Errorf("RenderHTML(%q) = %q, want %q", src, got, want)
		}
	}
}

// knownTag matches exactly the tags the renderer is allowed to emit, with
// exactly the attributes it is allowed to emit. Attribute values may not
// contain a quote or an angle bracket, so a value that broke out of its
// attribute would leave a stray character behind.
var knownTag = regexp.MustCompile(`</?(?:p|h[1-6]|em|strong|code|pre|a|img|ul|ol|li|blockquote|hr|br)(?: (?:href|src|alt|title|class)="[^"<>]*")*>`)

// assertNoRawMarkup strips the renderer's own tag set from html and fails if
// any angle bracket survives. Nothing from the input may reach the output
// unescaped, so every remaining `<` or `>` is a hole.
func assertNoRawMarkup(t *testing.T, html string) {
	t.Helper()
	stripped := knownTag.ReplaceAllString(html, "")
	if i := strings.IndexAny(stripped, "<>"); i >= 0 {
		start := max(i-40, 0)
		end := min(i+40, len(stripped))
		t.Errorf("unescaped markup in output near %q\nfull output:\n%s", stripped[start:end], html)
	}
}

// TestKnownTagRejectsUnknownMarkup is the mutation proof for the scanner
// above: it must not silently accept a tag or an attribute outside the set.
func TestKnownTagRejectsUnknownMarkup(t *testing.T) {
	bad := []string{
		`<script>alert(1)</script>`,
		`<p onclick="x">hi</p>`,
		`<a href="javascript:alert(1)" onmouseover="x">y</a>`,
		`<div>x</div>`,
		`<img src="a" onerror="alert(1)">`,
		`<p>a < b</p>`,
	}
	for _, s := range bad {
		if stripped := knownTag.ReplaceAllString(s, ""); !strings.ContainsAny(stripped, "<>") {
			t.Errorf("knownTag swallowed %q, leaving %q", s, stripped)
		}
	}
	good := `<p>ok</p>` + "\n" + `<a href="https://example.com" title="t">x</a>` + `<img src="https://e/x.png" alt="a">` + `<pre><code class="language-go">x</code></pre><hr><br>`
	if stripped := knownTag.ReplaceAllString(good, ""); strings.ContainsAny(stripped, "<>") {
		t.Errorf("knownTag rejected its own tag set, leaving %q", stripped)
	}
}
